"""add new fields in users model

Revision ID: 3cc7bd9aab8b
Revises: 7d6c4593af2e
Create Date: 2025-11-20 03:43:05.684825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cc7bd9aab8b"
down_revision: Union[str, Sequence[str], None] = "7d6c4593af2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=20), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=30), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
